// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgsrxajibgvzeylxhxsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZnc3J4YWppYmd2emV5bHhoeHN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUxMjM4NjgsImV4cCI6MjA1MDY5OTg2OH0.6Vid0h38pUr4C_y1yAOK4b8dPsQmISNKi25oLZ8_Qyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);